apiVersion: v1
kind: Service
metadata:
  name: kstreams-wordcount-service
  labels:
    app: kstreams-wordcount
spec:
  clusterIP: None
  selector:
    app: kstreams-wordcount
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kstreams-wordcount
spec:
  serviceName: "kstreams-wordcount-service"
  replicas: 1
  selector:
    matchLabels:
      app: kstreams-wordcount
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: kstreams-wordcount
    spec:
      containers:
      - name: kstreams-wordcount
        image: stephenharris13/wordcount:latest
        env:
          - name: BOOTSTRAP_SERVER
            value: kafka-3ca2c5e3-stephenh1988-adba.aivencloud.com:11435
          - name: TRUSTSTORE_PATH
            value: /etc/store/client.truststore.jks
          - name: KEYSTORE_PATH
            value: /etc/store/client.keystore.p12
          - name: TRUSTSTORE_PWD
            valueFrom:
              secretKeyRef:
                name: storepwd
                key: truststore
          - name: KEYSTORE_PWD
            valueFrom:
              secretKeyRef:
                name: storepwd
                key: keystore
    
        volumeMounts:
          - name: store
            readOnly: true
            mountPath: "/etc/store"
          - name: count-store
            mountPath: /tmp/kafka-streams
    
      volumes:
      - name: store
        secret:
          secretName: store      

  volumeClaimTemplates:
  - metadata:
      name: count-store
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

