version: '2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus-config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090

  app:
    image: stephenharris13/kafka-rollout-app
    env_file:
      - ./app/.env
    environment:
      - VERSION=1
    volumes:
      - ./../streams/store:/etc/cert
    ports:
      - '8080:8080'

  consumer:
    image: kafka-rollout-consumer
    env_file:
      - ./consumer/.env
    volumes:
      - ./../streams/store:/etc/cert
